language: node_js

node_js:
  - 0.6

before_script:
  - "export DISPLAY=:99.0" 
  - "sh -e /etc/init.d/xvfb start"
  - npm install connect
  - sudo node test/js/server.js &
  - sleep 5

notifications:
  irc: "irc.freenode.org#ds-dev"